# Generated by Django 3.1.4 on 2021-01-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBoard',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=300)),
                ('regdate', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'photo_board',
                'ordering': ['-b_id'],
                'managed': False,
            },
        ),
    ]
