# Generated by Django 3.1.4 on 2021-01-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
